Create/Search/Update Employer Users
mykytatishkin/csi-training-healthcare-2024 pull request #11
Opened 2024-02-22 21:40 UTC by devJUKI

2024-02-23 09:00 UTC, radislavkireev commented on src/CSI.IBTA.Administrator/Clients/UserServiceClient.cs
> +            if (_httpContextAccessor.HttpContext == null)
This comment is related to the classes EmployerClient, EmployerUserClient and UserServiceClient, I just do not want to repeat it 3 times. 

 _httpContextAccessor is not using and could be removed. 

Token receiving logic is repeatable. Lets consider reusing it with inheritance or any other approach you design.

2024-02-23 09:00 UTC, radislavkireev commented on src/CSI.IBTA.Administrator/Controllers/HomeController.cs
> +            var Employers = await _userServiceClient.GetEmployers(token);
```suggestion
            var employers = await _userServiceClient.GetEmployers(token);
```

2024-02-26 10:09 UTC, radislavkireev approved these changes

2024-02-26 12:33 UTC, GytisMas requested changes

2024-02-26 12:33 UTC, GytisMas commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +        public async Task<GenericHttpResponse<UpdatedUserDto>> PutUser(int userId, PutUserDto putUserDto)
Possibly redundant to have both PutUser and UpdateUser

2024-02-26 12:33 UTC, GytisMas commented on src/CSI.IBTA.UserService/Services/EmployersService.cs
> +            if (e == null) return new GenericHttpResponse<EmployerDto>(true, new HttpError("Emplyer not found", HttpStatusCode.NotFound), null);
Typo in error message

2024-02-26 12:33 UTC, GytisMas commented on src/CSI.IBTA.UserService/Services/EmployersService.cs
> +            if (e == null) return new GenericHttpResponse<bool>(true, new HttpError("Emplyer not found", HttpStatusCode.NotFound), false);
Typo in error message

2024-02-26 12:33 UTC, GytisMas commented on src/CSI.IBTA.Shared/DTOs/UserDto.cs
> +    public record PutUserDto(string UserName, string Password, string FirstName, string LastName, string PhoneNumber, string EmailAddress, string AddressState, string AddressStreet, string AddressCit
Possibly redundant to have both PutUserDto and UpdateUserDto

2024-02-26 13:28 UTC, GytisMas approved these changes

2024-02-26 13:29 UTC, merged