UI changes
mykytatishkin/csi-training-healthcare-2024 pull request #22
Opened 2024-03-13 16:26 UTC by mykytatishkin

2024-03-14 11:52 UTC, radislavkireev commented on src/CSI.IBTA.Administrator/Views/Home/Index.cshtml
> +        document.getElementById("employerBtn").setAttribute("class", "left view-btn-active");
the recommendation is to extract js code to a separate file and execute it as a handler of onload https://www.w3schools.com/jsref/event_onload.asp

2024-03-18 09:36 UTC, radislavkireev approved these changes

2024-03-19 16:06 UTC, GytisMas requested changes

2024-03-19 16:06 UTC, GytisMas commented on src/CSI.IBTA.Administrator/Views/Home/Index.cshtml
> +                                <button id="employerBtn" class="left view-btn-active" onclick="showEmployer()">Employer</button>
```suggestion
                                <button id="employerBtn" class="left view-btn-active" onclick="showEmployers()">Employer</button>
```

2024-03-19 16:34 UTC, GytisMas approved these changes

2024-03-19 17:27 UTC, merged