Create migrations and DataLayer projects. Add test migrations
mykytatishkin/csi-training-healthcare-2024 pull request #3
Opened 2024-02-06 21:28 UTC by VidasBui

2024-02-08 12:14 UTC, radislavkireev commented
Dup folder added.

2024-02-08 12:15 UTC, radislavkireev commented
Keep migrations in migrations assembly. Check sample https://github.com/dotnet/EntityFramework.Docs/blob/main/samples/core/Schemas/ThreeProjectMigrations/WebApplication1.sln

2024-02-08 12:17 UTC, radislavkireev requested changes

2024-02-08 12:17 UTC, radislavkireev commented on src/CSI.IBTA.DB.Migrations/Class1.cs
> +{
could be removed

2024-02-08 12:17 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/Models/CsiHealthcare2024Context.cs
> +public partial class CsiHealthcare2024Context : DbContext
Lets rename it to UserManagement context

2024-02-08 12:17 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/Models/CsiHealthcare2024Context.cs
> +        => optionsBuilder.UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=csi-healthcare-2024;Trusted_Connection=True;Encrypt=False;",
Conn string should be extracted to the config

2024-02-09 09:07 UTC, radislavkireev requested changes

2024-02-09 09:07 UTC, radislavkireev commented on src/CSI.IBTA.DB.Migrations/Migrations/20240206210505_AddNumberToTestTable.cs
> +#nullable disable
Delete testing migration

2024-02-09 09:07 UTC, radislavkireev commented on src/CSI.IBTA.DB.Migrations/Migrations/CsiHealthcare2024ContextModelSnapshot.cs
> +
Delete testing context

2024-02-09 11:10 UTC, radislavkireev approved these changes

2024-02-09 11:24 UTC, devJUKI approved these changes

2024-02-09 11:29 UTC, merged