Generic Repository & Unit of Work
mykytatishkin/csi-training-healthcare-2024 pull request #4
Opened 2024-02-07 22:20 UTC by devJUKI

2024-02-08 12:27 UTC, radislavkireev commented
Drop repos impls, except of Generic

2024-02-08 12:27 UTC, radislavkireev requested changes

2024-02-08 12:27 UTC, radislavkireev commented on src/CSI.IBTA.Shared/IConfiguration/IUnitOfWork.cs
> +
Lets move i-faces to Datalayer

2024-02-08 12:27 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/Repositories/GenericRepository.cs
> +        public abstract Task<bool> Upsert(T entity);
Lets make implementation of it. 

  //First attach the object to the table
            table.Attach(obj);
            //Then set the state of the Entity as Modified
            _context.Entry(obj).State = EntityState.Modified;

2024-02-08 15:04 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/DependencyInjection.cs
> +        {
add Registration of Dbcontext here

2024-02-08 15:04 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/Data/UnitOfWork.cs
> +            Accounts = new GenericRepository<User>(context, _logger);
```suggestion
            Users = new GenericRepository<User>(context, _logger);
```
I dunno what is the Db table name, but lets make naming consistent. DB name should match with DTO and Repo name to avoid confusion

2024-02-08 15:04 UTC, radislavkireev commented on src/CSI.IBTA.DataLayer/Interfaces/IGenericRepository.cs
>          Task<T?> GetById(int id);
Worse to mention that id is not necessary to be int, in general it should be generic. 
For now, lets go with what we have and try to use only int for PKs in DB.

2024-02-09 09:09 UTC, radislavkireev approved these changes

2024-02-09 12:29 UTC, ugis90 approved these changes

2024-02-09 12:29 UTC, merged