User service
mykytatishkin/csi-training-healthcare-2024 pull request #7
Opened 2024-02-14 10:42 UTC by GytisMas

2024-02-14 13:45 UTC, radislavkireev requested changes

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.DB.Migrations/Migrations/20240213111647_users-table.cs
> +    public partial class userstable : Migration
```suggestion
    public partial class Users: Migration
```

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.Shared/DTOs/UserDto.cs
> +    public record UserDto(int Id, string UserName, string FirstName, string LastName, int AccoundId, int EmployerId);
Lower case the param names

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.Shared/Settings/ImagesSettings.cs
> +        public static string[] GetAllowedFormats()
Suggestion is to extract file formats to the settings file, so the formats are configurable. You may do it in a separate PR,  this one could be approved when you done with other notes.

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.Shared/Utils/PasswordHasher.cs
> +    public static class PasswordHasher
Lets keep it as is, but for the future  - lest avoid static classes, until they are extensions or super simple. 
They could not be mocked for the unit test which is disadvantage.

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            await _unitOfWork.Accounts.All();
EF should solve the mappings for you if you had map created, relations should not be solved manually.
Check this article: https://learn.microsoft.com/en-us/ef/core/modeling/relationships

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            await _unitOfWork.Accounts.All();
The same as above - relations should be handled by EF mappings, not manually. 
Also, in order to get 1 user, your code queries all Users + all employers + all relations between then. 
If we gonna have 10k users more that would be very slow and expensive operation.

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            await _unitOfWork.Accounts.Add(newAccount);
User EF mappings, you should not manually solve relations. 
This note relates to the rest of the methods, I am not gonna repeat it, but all the methods of this class should be refactored. 
Ask colleagues to help and parallel the efforts if needed.

2024-02-14 13:45 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Utils/FileUtils.cs
> +    internal static class FileUtils
Extract i-face, do the regular class and inject it with DI.

2024-02-15 16:16 UTC, mykytatishkin commented on src/CSI.IBTA.DB.Migrations/Migrations/20240214164641_Settings.cs
> +                    Condition = table.Column<string>(type: "nvarchar(max)", nullable: false),
Why `nvarchar(max)`? nvarchar(50) or (100) isnt enough?

2024-02-15 16:35 UTC, mykytatishkin approved these changes

2024-02-19 14:01 UTC, radislavkireev requested changes

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +        public async Task<GenericResponse<UserDto[]>> GetAllUsers(HttpContext httpContext)
Do not pass httpContext to the business service. Business layer should not have a dependency on Web context

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +        {
do not pass httpContext, but IPrincipal ( httpContext.User)

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            if (!IsNextSuperiorRole(httpContext.User, createUserDto.Role))
do not pass httpContext, but IPrincipal ( httpContext.User)

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            var authUserId = httpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
do not pass httpContext, but IPrincipal ( httpContext.User)

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +            var user = await _unitOfWork.Users
do not pass httpContext, it is not even used here

2024-02-19 14:01 UTC, radislavkireev commented on src/CSI.IBTA.UserService/Services/UsersService.cs
> +    internal class UsersService : IUsersService
You don't need to verify httpCOntext.User permissions at UsersService if it is already done at UserController. 
So, my vote would be to verify roles and credentials in controllers

2024-02-19 15:14 UTC, radislavkireev approved these changes

2024-02-19 15:49 UTC, merged