Database project
mykytatishkin/csi-training-healthcare-2024 pull request #8
Opened 2024-02-14 14:29 UTC by mykytatishkin

Also, I am waiting for the answer about blob in the work chat

2024-02-14 15:22 UTC, radislavkireev approved these changes

2024-02-15 12:04 UTC, VidasBui requested changes

2024-02-15 12:04 UTC, VidasBui commented on src/CSI.IBTA.DB.AuthDatabase/Account.sql
There is no field for Account role

2024-02-15 12:05 UTC, mykytatishkin commented on src/CSI.IBTA.DB.AuthDatabase/Account.sql
Sorry, forgot about it, I'll fix in a few moments

2024-02-15 12:37 UTC, mykytatishkin commented on src/CSI.IBTA.DB.AuthDatabase/Account.sql
done

2024-02-15 12:53 UTC, VidasBui approved these changes

2024-02-15 14:11 UTC, merged